#! /bin/sh

# ------------------------------------------------------------------------------
#
# Basler dart BCON for LVDS Development Kit
# http://www.baslerweb.com
#
# ------------------------------------------------------------------------------
#
# Copyright (c) 2017-2018, Basler AG
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from this
#    software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# ------------------------------------------------------------------------------
#
## @file    setup_leds
##
## @brief   Setup GPIO LEDs
##
## @author  Thomas Köller
##
## @date    20.02.2017
##
## @copyright (c) 2017-2018, Basler AG
##
## @license BSD 3-Clause License


linkdir="/run/bconctl/leds"

setup ()
{
    name="led-user$1"
    cd "${name}"
    ln -s "${PWD}" "${linkdir}/${name}"
    chmod 666 'brightness' 'trigger'
    echo 'none' >trigger
    echo '0' >'brightness'
    cd ..
}

cd /sys/devices/soc0/gpio-leds/leds

case "$ACTION" in
    add)
        test -d "${linkdir}" || mkdir -p "${linkdir}"
        setup 0
        setup 1
        setup 2
        ;;
    remove)
        rm -rf "${linkdir}"
        ;;
esac
