#! /bin/sh

# ------------------------------------------------------------------------------
#
# Basler dart BCON for LVDS Development Kit
# http://www.baslerweb.com
#
# ------------------------------------------------------------------------------
#
# Copyright (c) 2017-2018, Basler AG
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from this
#    software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# ------------------------------------------------------------------------------
#
## @file    setup_gpio
##
## @brief   Setup GPIOs
##
## @author  Thomas Köller
##
## @date    25.01.2017
##
## @copyright (c) 2017-2018, Basler AG
##
## @license BSD 3-Clause License


linkdir="/run/bconctl/gpio"

setup ()
{
    echo "${1}" >export
    echo 'out' >gpio${1}/direction
    echo '0' >gpio${1}/active_low
    echo '0' >gpio${1}/value
    chmod 666 gpio${1}/active_low
    chmod 666 gpio${1}/direction
    chmod 666 gpio${1}/value
    lnk=`readlink gpio${1}`
    lnk=`realpath "${lnk}"`
    ln -s "${lnk}" "${linkdir}/gpio_$2"
}

cd /sys/class/gpio

case "$ACTION" in
    add)
        test -d "${linkdir}" || mkdir -p "${linkdir}"
        setup 976 camera_address
        setup 977 camera_power
        ;;
    remove)
        rm -rf "${linkdir}"
        ;;
esac
